<a href="https://colab.research.google.com/github/enzoimiola91/projet-sommeil-etudiant/blob/main/AiboudImiola.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Projet d'analyse de données : Déterminants du sommeil chez les étudiants
"""Membres du binôme : IMIOLA Enzo & AIBOUD Yanis

Cadre : Rendu de dossier et préparation d'oral

Lien vers la base de données : Kaggle - Student Sleep Patterns (Arsalan Jamal): https://www.kaggle.com/datasets/arsalanjamal002/student-sleep-patterns

### Problématique de recherche retenue :
« Entre le temps passé sur les écrans et la charge de travail, qu'est-ce qui détériore le plus le sommeil des étudiants, et peut-on prédire ceux qui risquent d'être en dette de sommeil ? »"""

"Membres du binôme : IMIOLA Enzo & AIBOUD Yanis\n\nCadre : Rendu de dossier et préparation d'oral  \n\nLien vers la base de données : Kaggle - Student Sleep Patterns (Arsalan Jamal): https://www.kaggle.com/datasets/arsalanjamal002/student-sleep-patterns\n\n### Problématique de recherche retenue :\n« Entre le temps passé sur les écrans et la charge de travail, qu'est-ce qui détériore le plus le sommeil des étudiants, et peut-on prédire ceux qui risquent d'être en dette de sommeil ? »"

In [14]:
import pandas as pd

# 1. Lien direct public vers le fichier CSV hébergé sur GitHub
url = "https://raw.githubusercontent.com/enzoimiola91/projet-sommeil-etudiant/refs/heads/main/student_sleep_patterns.csv"

# 2. Chargement automatique dans Pandas
df = pd.read_csv(url)

# 3. Vérification immédiate
print(f"Jeu de données chargé avec succès : {df.shape[0]} lignes et {df.shape[1]} colonnes.")
df.head(3)

Jeu de données chargé avec succès : 500 lignes et 14 colonnes.

,Student_ID,Age,Gender,University_Year,Sleep_Duration,Study_Hours,Screen_Time,Caffeine_Intake,Physical_Activity,Sleep_Quality,Weekday_Sleep_Start,Weekend_Sleep_Start,Weekday_Sleep_End,Weekend_Sleep_End
0,1,24,Other,2nd Year,7.7,7.9,3.4,2,37,10,14.16,4.05,7.41,7.06
1,2,21,Male,1st Year,6.3,6.0,1.9,5,74,2,8.73,7.10,8.21,10.21
2,3,22,Male,4th Year,5.1,6.7,3.9,5,53,5,20.00,20.47,6.88,10.92

In [15]:
# 1. Visualisation des 5 premières lignes
print("--- 5 PREMIÈRES LIGNES ---")
display(df.head())

# 2. Dimensions de la base (shape)
print("\n--- DIMENSIONS DU JEU DE DONNÉES ---")
print(f"Nombre d'observations (lignes) : {df.shape[0]}")
print(f"Nombre de variables (colonnes) : {df.shape[1]}")

# 3. Types de variables
print("\n--- TYPES DE DONNÉES (DTYPES) ---")
print(df.dtypes)

# 4. Vérification des observations nulles et doublons
print("\n--- VALEURS MANQUANTES PAR COLONNE ---")
print(df.isnull().sum())

print("\n--- NOMBRE DE DOUBLONS STRICTS ---")
print(f"Doublons détectés : {df.duplicated().sum()}")

--- 5 PREMIÈRES LIGNES ---

,Student_ID,Age,Gender,University_Year,Sleep_Duration,Study_Hours,Screen_Time,Caffeine_Intake,Physical_Activity,Sleep_Quality,Weekday_Sleep_Start,Weekend_Sleep_Start,Weekday_Sleep_End,Weekend_Sleep_End
0,1,24,Other,2nd Year,7.7,7.9,3.4,2,37,10,14.16,4.05,7.41,7.06
1,2,21,Male,1st Year,6.3,6.0,1.9,5,74,2,8.73,7.10,8.21,10.21
2,3,22,Male,4th Year,5.1,6.7,3.9,5,53,5,20.00,20.47,6.88,10.92
3,4,24,Other,4th Year,6.3,8.6,2.8,4,55,9,19.82,4.08,6.69,9.42
4,5,20,Male,4th Year,4.7,2.7,2.7,0,85,3,20.98,6.12,8.98,9.01

--- DIMENSIONS DU JEU DE DONNÉES ---
Nombre d'observations (lignes) : 500
Nombre de variables (colonnes) : 14

--- TYPES DE DONNÉES (DTYPES) ---
Student_ID               int64
Age                      int64
Gender                  object
University_Year         object
Sleep_Duration         float64
Study_Hours            float64
Screen_Time            float64
Caffeine_Intake          int64
Physical_Activity        int64
Sleep_Quality            int64
Weekday_Sleep_Start    float64
Weekend_Sleep_Start    float64
Weekday_Sleep_End      float64
Weekend_Sleep_End      float64
dtype: object

--- VALEURS MANQUANTES PAR COLONNE ---
Student_ID             0
Age                    0
Gender                 0
University_Year        0
Sleep_Duration         0
Study_Hours            0
Screen_Time            0
Caffeine_Intake        0
Physical_Activity      0
Sleep_Quality          0
Weekday_Sleep_Start    0
Weekend_Sleep_Start    0
Weekday_Sleep_End      0
Weekend_Sleep_End      0
dtype: int64

--- NOMBRE DE DOUBLONS STRICTS ---
Doublons détectés : 0